### ISSUE TITLE
グラボの買い替え

### ISSUE THREAD

**Issue by atnanasi** [atnanasi/atnanasi#1]
おんぼろグラボを使いつづけるのはつらい

**Comment by sirotama** [comment]
GTX TITAN X x 2 SLI

**Comment by otofune** [comment]
AMDがそろそろ降臨するのでちょっと保留して欲しいみたいなのある Vegaっていうアーキテクチャなんですけど

**Comment by Tosuke** [comment]
早く買って

**Comment by atnanasi** [comment]
しろたまくんからGTX970を2万で貰うぞ？

**Comment by atnanasi** [comment]
おまたせ、GTX960しかなかったけどいいかな?
