### ISSUE TITLE
#p4dhouse 移送

### ISSUE THREAD

**Issue by atnanasi** [atnanasi/atnanasi#10]
- [x] 携帯端末
- [x] PC
- [x] 財布
- [x] 通帳
- [x] 半袖上着2
- [x] ズボン1
- [x] パンツ3
- [x] 靴下2
- [x] お茶2
- [x] はぶらし
- [x] ティッシュ
- [x] 薬

**Comment by atnanasi** [comment]
- [ ] 充電器

**Comment by atnanasi** [comment]
- [ ] Libertouch

**Comment by atnanasi** [comment]
- [ ] マスク

**Comment by potato4d** [comment]
ワンチャンバスがくれるけどアイマスクとかあったらQoL上がったりするぞ

あと4dへの愛もあるとなお良いぞ

**Comment by atnanasi** [comment]
- [ ] アイマスク

**Comment by atnanasi** [comment]
オタク荷造り完了

**Comment by potato4d** [comment]
God

**Comment by atnanasi** [comment]
帰ってきたので終わり
