### ISSUE TITLE
#4dhouse 移送 第二弾

### ISSUE THREAD

**Issue by potato4d** [atnanasi/atnanasi#11]
#hojiroLT 出るぞ

**Comment by atnanasi** [comment]
あのさあ

**Comment by otofune** [comment]
:boom:

**Comment by potato4d** [comment]
![image](https://cloud.githubusercontent.com/assets/6993514/22213117/556def70-e1d6-11e6-8d3e-63f1d3b269e9.png)

**Comment by atnanasi** [comment]
良くないポイント高いんだけど

**Comment by otofune** [comment]
完全に良いでしょ

**Comment by atnanasi** [comment]
- [ ] 携帯端末
- [x] PC
- [x] 財布
- [x] 通帳
- [x] 半袖上着2
- [x] ズボン1
- [x] パンツ3
- [x] 靴下2
- [x] お茶2
- [x] はぶらし
- [x] ティッシュ
- [x] 薬

**Comment by otofune** [comment]
重たいもの多くない？

**Comment by atnanasi** [comment]
分かる

**Comment by atnanasi** [comment]
LT喋ったぞ？

**Comment by atnanasi** [comment]
無事に帰宅した
